---

- name: create edu-sharing.conf
  template:
    src: edu-sharing.conf.j2
    dest: "{{repository_volume_config_cluster_path.stdout}}/edu-sharing.override.conf"
  when: edu_config_file == 'edu-sharing.conf'

- include_tasks: youtube.yml  
  when: connect_content_youtube
  tags:
    - youtube

- include_tasks: pixabay.yml
  when: connect_content_pixabay
  tags:
    - pixabay

- include_tasks: lms.yml
  tags:
    - lms

- include_tasks: shibboleth_after.yml
  when: edu_configure_shibboleth is defined and edu_configure_shibboleth
  tags:
    - shibboleth
