---
- name: check if esrender initialization is complete already
  uri:
    url: '{{esrender_url}}/application/esmain/metadata.php'
    method: GET
    status_code: [200, 500]
    return_content: true
  register: esrender_init_meta
  
- set_fact:
    esrender_init_complete: "{{ (esrender_init_meta['status'] == 200) and (esrender_init_meta['content'].startswith('<?xml')) }}"

- name: "wait for tomcat to come up"
  uri:
    url: '{{edu_sharing_url}}'
    timeout: 60
    status_code: 200
  register: result
  until: result.status == 200
  retries: 5
  delay: 1
  when: not esrender_init_complete

- include: http.yml
  when: esrender_exec_method == 'http'

- include: cli.yml
  become: true
  when: esrender_exec_method == 'cli'
  tags: root-task
