---
- name: check if esrender initialization is complete already
  uri:
    url: '{{esrender_url}}/application/esmain/metadata.php'
    method: GET
    status_code: [200, 500]
  register: esrender_init_meta

- name: "wait for tomcat to come up"
  uri:
    url: 'http://{{edu_sharing_host}}/edu-sharing'
    timeout: 60
    status_code: 200
  register: result
  until: result.status == 200
  retries: 5
  delay: 1
  when: "esrender_init_meta['status'] == 500"

- name: esrender installation step 1
  uri:
    url: '{{esrender_url}}/install/install.php'
    method: POST
    body_format: form-urlencoded
    body: step=1&LANG=1&terms_accepted=0&terms_accepted=1&send=
  when: "esrender_init_meta['status'] == 500"

- name: esrender installation step 2
  uri:
    url: '{{esrender_url}}/install/install.php'
    method: POST
    body_format: form-urlencoded
    body:
      step: 2
      LANG: 1
      RS_URL: '{{esrender_url}}/'
      BASE_DIR: /var/www/esrender/
      DATA_DIR: /var/cache/esrender/
      REPO_URL: 'http://{{edu_sharing_host}}/edu-sharing/'
      DB_DRIVER: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: '{{esrender_db.port}}'
      DB_USER: '{{esrender_db.user}}'
      DB_PASS: '{{esrender_db.password}}'
      DB_NAME: '{{esrender_db.name}}'
      send: ''
  when: "esrender_init_meta['status'] == 500"

- name: esrender installation step 3
  uri:
    url: '{{esrender_url}}/install/install.php'
    method: POST
    body_format: form-urlencoded
    body: step=3&LANG=1&send=
  when: "esrender_init_meta['status'] == 500"
