- name: Copy alfviral AMP
  copy:
    src: '{{ antivirus_alfviral_amp_filename }}'
    dest: "{{ alf_amp_destination }}"
  when: alf_amp_destination is defined

- name: Install alfviral
  command:
    chdir: '{{ alf_home }}/bin'
    cmd: 'java -jar alfresco-mmt.jar install ../amps/{{ antivirus_alfviral_amp_filename | basename }} {{tomcat_home}}/webapps/alfresco.war -verbose -nobackup'
  when: install_alfviral | default(false) | bool
