---
- name: Clear hideMainMenu entries from client config
  xml:
    path: '{{ hide_main_menu_config_xml_path }}'
    xpath: '/config/values/hideMainMenu'
    state: absent
    pretty_print: yes

- name: add hideMainMenu entry to client config
  xml:
    path: '{{ hide_main_menu_config_xml_path }}'
    xpath: '/config/values'
    add_children: '<hideMainMenu>{{ item }}</hideMainMenu>'
    input_type: xml
    pretty_print: yes
  with_items: '{{edu_hide_main_menus | default([], true) }}'