---
- name: register LMS - add app-XXX.properties.xml
  template:
    src: lms.properties.xml.j2
    dest: "{{lms_path}}/app-{{ item.appid }}.properties.xml"
  loop: "{{ edu_connected_lms | default([], true) }}"

- name: register LMS - edit applicationfiles in ccapp-registry.properties.xml
  lineinfile:
    backrefs: yes
    path: "{{lms_path}}/ccapp-registry.properties.xml"
    line: '<entry key="applicationfiles">\g<start>\g<end>,app-{{ item.appid }}.properties.xml</entry>'
    regexp: '^\s*<entry key="applicationfiles">(?P<start>(?:(?!,app-{{ item.appid }}.properties.xml).)*)(,app-{{ item.appid }}.properties.xml)?(?P<end>.*?)</entry>'
  loop: "{{ edu_connected_lms | default([], true) }}"
