---
- name: Get the path config-edu-sharing docker volume.
  shell: |
    sg docker -c "docker volume inspect --format '{{ '{{' }}.Mountpoint{{ '}}' }}'  $(sg docker -c "docker volume ls -q |grep '_repository-service-volume-config-edu-sharing'")"
  register: repository_config_edu_sharing_path
  ignore_errors: true
  tags:
    - edu-sharing-config

- name: Let's wait until all required folders are created by docker container
  become: true
  wait_for:
    path: "{{ item }}"
    state: present
  retries: 10
  delay: 10
  loop:
    - "{{repository_config_edu_sharing_path.stdout}}/assets/images/"
    - "{{repository_config_edu_sharing_path.stdout}}/assets/i18n/"

- include_tasks: edu-sharing-assets.yml
  args:
    apply:
      become: yes
  when: (repository_config_edu_sharing_path.stdout is defined) and (repository_config_edu_sharing_path.stdout != "")
  tags:
    - edu-sharing-config