---
- name: Install apache
  apt:
    name: ["apache2"]
    state: "present"
  tags:
  - packages

- name: apache - add virtual hosts
  template:
    src: '{{ item.path }}'
    dest: '/etc/apache2/sites-available/{{ item.name }}.conf'
  loop: '{{ apache2_conf_templates }}'
  notify:
    - restart apache2

- name: apache - enabled mod
  apache2_module:
    name: "{{ item }}"
    state: "present"
  loop: '{{ apache2_modules }}'
  notify:
    - restart apache2

- name: a2dissite default
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - restart apache2

- name: a2ensite
  file:
    path: '/etc/apache2/sites-enabled/{{ item.name }}.conf'
    src: '../sites-available/{{ item.name }}.conf'
    state: link
  loop: '{{ apache2_conf_templates }}'
  notify:
    - restart apache2
