---
edu_sharing_archive_url: https://artifacts.edu-sharing.com/repository/maven-remote/org/edu_sharing/edu_sharing-projects-community-deploy-docker-compose/7.0.0/edu_sharing-projects-community-deploy-docker-compose-7.0.0-bin.zip

# In newer versions Edu-sharing will change the deploy command so we need to update it here
# deploy docker images to server
edu_sharing_deploy_command: 'sg docker -c "./deploy.sh start"'
edu_sharing_restart_command: 'sg docker -c "./deploy.sh restart"'
# remove docker images from server
edu_sharing_undeploy_command: sg docker -c "./deploy.sh stop"
edu_sharing_remove_containers_command: |
     yes | sg docker -c "./deploy.sh remove"

# this will remove images,containers adn volumes, so be carefully when we use it.
edu_sharing_purge_all_command: |
     yes | sg docker -c "./deploy.sh purge"