---
  - include: Debian.yml
    when: ansible_distribution == 'Debian'

  - name: Find path for new JAVA binary
    shell: update-alternatives --query java | grep Alternative | grep zulu{{java_version}} | cut -f 2 -d " "
    register: java_bin_path
    changed_when: false

  - name: Update Java alternative
    alternatives:
      name: java
      path: "{{java_bin_path.stdout}}"
    when: java_register_alternative is defined and java_register_alternative

  - name: Check if Java installation directory exists
    stat:
      path: "{{ java_base_path }}/zulu{{ java_version }}/bin/java"
    register: java_bin_stat

  - name: java_home directory variable
    set_fact:
      java_home: "{{ java_base_path }}/zulu{{ java_version }}"
    when: java_bin_stat.stat.exists


  - name: Register JAVA_HOME env variable
    lineinfile: dest=/etc/profile regexp="^(export JAVA_HOME=)" state=present line="export JAVA_HOME={{ java_base_path }}/zulu{{ java_version }}"
    when: (java_register_env is defined and java_register_env) and java_bin_stat.stat.exists