---
- name: Ensure and clean the alfviral directory
  include_tasks: ensure_and_clean_directory.yml
  vars:
    target_directory: "{{ edu_docker_inst_dir }}/custom-repository-service/alfviral/"

# Include the alfviral amp file
- name: Copy alfviral AMP
  copy:
    src: '{{ antivirus_alfviral_amp_filename }}'
    dest: "{{ edu_docker_inst_dir }}/custom-repository-service/alfviral/"

- name: modify reinstall.sh script to accept alfviral amp
  blockinfile:
    path: "{{ edu_docker_inst_dir }}/custom-repository-service/reinstall.sh"
    insertbefore: "^libcheck.sh$"
    marker: "# Add alfviral amp file"
    block: |
        if [[ -d amps/alfviral ]] ; then
          java -jar bin/alfresco-mmt.jar install amps/alfviral tomcat/webapps/alfresco -directory -nobackup -force
        fi