---
- name: Ensure and clean the esupdate directory
  include_tasks: ensure_and_clean_directory.yml
  vars:
    target_directory: "{{ edu_docker_inst_dir }}/custom-repository-service/esupdate/"

# Include the es-update-oersi amp file
- name: Copy es-update-oersi AMP.
  copy:
    src: '{{ es_update_oersi_amp_filename }}'
    dest: "{{ edu_docker_inst_dir }}/custom-repository-service/esupdate/"


- name: modify reinstall.sh script to accept es-update-oersi amp
  blockinfile:
    path: "{{ edu_docker_inst_dir }}/custom-repository-service/reinstall.sh"
    insertbefore: "^libcheck.sh$"
    marker: "# Add es-update-oersi amp file"
    block: |
        if [[ -d amps/esupdate ]] ; then
          java -jar bin/alfresco-mmt.jar install amps/esupdate tomcat/webapps/alfresco -directory -nobackup -force
        fi