---
- name: Set up dbType
  become: yes
  shell: '{{ onlyoffice_json}} -I -e ''this.services.CoAuthoring.sql.type  = "{{ onlyoffice_db_type }}"'''
  notify: restart onlyoffice
  when: (onlyoffice_db_type is defined) and (onlyoffice_db_type != "") and (onlyoffice_db_type is not none)

- name: Set up dbHost
  become: yes
  shell: '{{ onlyoffice_json}} -I -e ''this.services.CoAuthoring.sql.dbHost  = "{{ onlyoffice_db_host }}"'''
  notify: restart onlyoffice
  when: (onlyoffice_db_host is defined) and (onlyoffice_db_host != "") and (onlyoffice_db_host is not none)

- name: Set up dbPort
  become: yes
  shell: '{{ onlyoffice_json}} -I -e ''this.services.CoAuthoring.sql.dbPort  = "{{ onlyoffice_db_port }}"'''
  notify: restart onlyoffice
  when: (onlyoffice_db_port is defined) and (onlyoffice_db_port != "") and (onlyoffice_db_port is not none)

- name: Set up DB dbName
  become: yes
  shell: '{{ onlyoffice_json}} -I -e ''this.services.CoAuthoring.sql.dbName  = "{{ onlyoffice_db_name }}"'''
  notify: restart onlyoffice
  when: (onlyoffice_db_name is defined) and (onlyoffice_db_name != "") and (onlyoffice_db_name is not none)

- name: Set up DB dbUser
  become: yes
  shell: '{{ onlyoffice_json}} -I -e ''this.services.CoAuthoring.sql.dbUser  = "{{ onlyoffice_db_user }}"'''
  notify: restart onlyoffice
  when: (onlyoffice_db_user is defined) and (onlyoffice_db_user != "") and (onlyoffice_db_user is not none)

- name: Set up DB dbPass
  become: yes
  shell: '{{ onlyoffice_json}} -I -e ''this.services.CoAuthoring.sql.dbPass  = "{{ onlyoffice_db_password }}"'''
  notify: restart onlyoffice
  when: (onlyoffice_db_password is defined) and (onlyoffice_db_password != "") and (onlyoffice_db_password is not none)

# Rabbit MQ configuration

- name: Set up rabbitmq url
  become: yes
  shell: '{{ onlyoffice_json}} -I -e ''this.rabbitmq.url  = "{{ onlyoffice_rabbitmq_url }}"'''
  notify: restart onlyoffice
  when: (onlyoffice_rabbitmq_url is defined) and (onlyoffice_rabbitmq_url != "") and (onlyoffice_rabbitmq_url is not none)
