---
#- name: stop alfresco
#  shell: '{{alf_home}}/alfresco.sh stop'

- name: download and extract sources
  unarchive:
    remote_src: yes
    src: '{{edu_sharing_archive_url}}'
    dest: "{{edu_inst_dir}}"
    creates: "{{edu_home}}"

- name: edit build.properties
  lineinfile:
    path: '{{ edu_home }}/build.properties'
    line: 'webserver.home={{alf_home}}/tomcat'
    regexp: '^webserver.home=.*$'

- name: edit call-ant.sh
  replace:
    path: '{{ edu_home }}/call-ant.sh'
    replace: '{{alf_home}}/java/bin/java '
    regexp: '^java '

- name: make install.sh executable
  file:
    path: '{{ edu_home }}/install.sh'
    mode: 'a+x'

- name: run install.sh
  shell: '{{ edu_home }}/install.sh'
  args:
    chdir: '{{ edu_home }}'

- name: edit password in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ alf_home }}/tomcat/shared/classes/homeApplication.properties.xml'
    line: '<entry key="password">{{alf_password}}</entry>'
    regexp: '^<entry key="password">'

- name: edit host in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ alf_home }}/tomcat/shared/classes/homeApplication.properties.xml'
    line: '<entry key="host">{{alf_host}}</entry>'
    regexp: '^<entry key="host">'

- name: edit domain in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ alf_home }}/tomcat/shared/classes/homeApplication.properties.xml'
    line: '<entry key="domain">{{alf_domain}}</entry>'
    regexp: '^<entry key="domain">'

- name: edit port in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ alf_home }}/tomcat/shared/classes/homeApplication.properties.xml'
    line: '<entry key="port">{{alf_port}}</entry>'
    regexp: '^<entry key="port">'

- name: edit tomcat/shared/classes/alfresco-global.properties
  lineinfile:
    path: '{{ alf_home }}/tomcat/shared/classes/alfresco-global.properties'
    line: 'authentication.ticket.useSingleTicketPerUser=false'
    regexp: '^authentication.ticket.useSingleTicketPerUser=false$'
