---
- name: Ensure python-lxml packages are present
  apt:
    name: ["python-lxml"]
  become: yes
  tags:
  - packages
  - root-task

- name: php - install base packages
  apt:
    name: ["php", "php-cli", "php-gd", "php-curl", "php-mysql", "php-pgsql", "php-xml", "php-zip", "php-soap", "php-mbstring", "php-dom", "php-iconv", "php-fileinfo", "php-sockets", "php-wddx", "php-date", "php-sqlite3"]
    state: "present"
  become: yes
  tags:
  - packages
  - root-task

- name: Ensures inst-dir exists
  file: path='{{esrender_download_dir}}' state=directory

- name: download esrender sources
  get_url:
    url: '{{esrender_archive_url}}'
    dest: "{{esrender_download_dir}}/esrenderingservice.tar.gz"
    force: '{{ esrender_force_download }}'
  when: esrender_archive_retrieve_method == "download"

- name: Copy local esrender sources
  copy:
    src: "{{ esrender_local_archive_path }}"
    dest: "{{esrender_download_dir}}/esrenderingservice.tar.gz"
  when: esrender_archive_retrieve_method == "copy-local"

- name: Remove old esrender installation (base dir)
  file: path='{{ esrender_base_dir }}' state=absent
  when: esrender_remove_existing

- name: Remove old esrender installation (cache dir)
  file: path='{{ esrender_cache_dir }}' state=absent
  when: esrender_remove_existing

- name: extract esrender sources
  unarchive:
    remote_src: yes
    src: '{{esrender_download_dir}}/esrenderingservice.tar.gz'
    owner: "www-data"
    group: "www-data"
    dest: '{{esrender_document_root}}'
    extra_opts:
      - --transform
      - s/^edu-sharing-community-services-rendering-[0-9.a-zA-Z-]*/esrender/
  notify:
    - restart apache2

- name: chown esrender (base dir)
  file: path='{{ esrender_base_dir }}' state=directory owner=www-data group=www-data

- name: create /var/cache/esrender
  file:
    path: '{{esrender_cache_dir}}'
    state: "directory"
    owner: "www-data"
    group: "www-data"
  notify:
    - restart apache2

- name: Copy custom configuration files for esrender application
  template:
    src: '{{item[0]}}'
    dest: '{{ esrender_base_dir }}/modules/{{item[1]}}'
  loop: '{{ esrender_custom_config_files | default([], true) }}'

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
