---
- name: Ensure mysql python packages are present
  package:
    name: python-mysqldb

- name: Create a new database with name 'esrender'
  mysql_db:
    name: '{{esrender_db.name}}'
    config_file: /etc/my.cnf.d/mysql.cnf
    state: present

- name: Create esrender database user
  mysql_user:
    name: '{{esrender_db.user}}'
    password: '{{esrender_db.password}}'
    priv: '{{esrender_db.name}}.*:ALL'
