---

# This part here is used only for migration, and in next optimization we will 
# find a better way to implement them but for now we will keep here since we are in cleaning process now
alf_name: alfresco-community-distribution-201707
alf_inst_dir: "{{base_dir}}"
alf_home: "{{alf_inst_dir}}/{{alf_name}}"

# db_types: 'postgresql', 'mariadb' (edu-sharing 4.2 supports only 'postgresql', no migration on change)
alfresco_db_type: postgresql
alfresco_db:
  name: alfresco
  user: alfresco
  password: alfresco
