---
edu_sharing_host: 192.168.98.101
edu_sharing_domain: '{{edu_sharing_host}}'

solr_host: '{{edu_sharing_host}}'

esrender_host: 192.168.98.102
esrender_url: 'http://{{esrender_host}}/esrender'

mariadb_port: 3306
esrender_db:
  name: esrender
  user: esrender
  password: esrender

tomcat_port: 8080
tomcat_shutdown_port: 8005
tomcat_ssl_port: 8443
tomcat_ajp_port: 8009

base_dir: "{{ansible_env.HOME}}"

esrender_document_root: '/var/www'
esrender_base_dir: '{{esrender_document_root}}/esrender'
esrender_cache_dir: '/var/cache/esrender'

moodle_host: 192.168.98.105
moodle_url: "http://{{moodle_host}}"