---
edu_sharing_host: 192.168.98.101
edu_sharing_domain: '{{edu_sharing_host}}'
edu_sharing_url: '{{ edu_sharing_protocol | default("http") }}://{{edu_sharing_host}}/edu-sharing'
edu_version: 8.1.0
solr_host: '{{edu_sharing_host}}'

esrender_host: 192.168.98.101
esrender_proxy: '{{ esrender_host }}'
esrender_url: '{{ edu_sharing_protocol | default("http") }}://{{ esrender_proxy }}/edu-sharing/esrender'

clamav_host: 192.168.98.101
clamav_proxy: "{{clamav_host}}"

edu_connector_host: 192.168.98.104
edu_connector_proxy: "{{edu_connector_host}}"
install_splash: false
enable_edu_connector: false
# db_types: 'postgresql', 'mariadb' (no migration on change)
esrender_db_type: mariadb
esrender_db:
  name: esrender
  user: esrender
  password: esrender
  
postgres_tmp_root_password: xxx

base_dir: "{{ansible_env.HOME}}"

esrender_document_root: '/var/www'
esrender_base_dir: '{{esrender_document_root}}/esrender'
esrender_cache_dir: '/var/cache/esrender'

alf_password: admin

script_dir: '{{ base_dir }}/bin'

# enable / disable the edu-sharing backup process: present|absent
backup_process_state: absent
backup_db_user: oerbackup
backup_db_password: changeme
backup_schedule_hour: 2
backup_path: '{{ base_dir }}/backup'
backup_bin: '{{ script_dir }}'

apache_conf_servername: # use as apache2 ServerName Directive, if set - see http://httpd.apache.org/docs/2.2/en/mod/core.html#servername
apache_conf_usecanonicalname: # use as apache2 UseCanonicalName Directive, if set. Example: On - see http://httpd.apache.org/docs/2.2/en/mod/core.html#usecanonicalname

# Recommended RAM for ClamAV :
#    Minimum: 3 GiB
#    Preferred: 4 GiB
install_antivirus: false