---
es_proxy_vhost: true
tomcat_user_solr_identity: true
use_esguest_user: true
# map of permssions that should be adjusted for the esguest user
# key: Key of the permission (see list of available permissions: curl -X GET --header 'Accept: application/json' 'http://<YOURHOST>/edu-sharing/rest/admin/v1/toolpermissions/esguest')
# value: ALLOWED | DENIED | UNDEFINED (see https://github.com/edu-sharing/Edu-Sharing/blob/develop/Backend/src/org/edu_sharing/service/admin/model/ToolPermission.java)
esguest_permissions:
  "TOOLPERMISSION_GLOBAL_AUTHORITY_SEARCH": "DENIED"

connect_content_pixabay: false
pixabay_apikey: CHANGE_ME

connect_content_youtube: false
youtube_apikey: CHANGE_ME

register_moodle: false
moodle_host: 192.168.98.105
moodle_url: "http://{{moodle_host}}"

edu_version: 5.0.0
edu_sharing_archive_url: https://github.com/edu-sharing/Edu-Sharing/releases/download/5.0.0/edu-sharing_5.0.0.2020-02-05-5f0546557.zip
# method how to retrieve the edu-sharing archive that should be installed
#  'download' - use the archive from 'edu_sharing_archive_url'
#  'copy-local' - copy the archive from the local host in 'edu_sharing_local_archive_path'
edu_sharing_archive_retrieve_method: download
edu_sharing_local_archive_path:

# possibility to add an archive with custom modifications to edu-home
edu_sharing_custom_installation: false
edu_sharing_custom_archive_path:

edu_inst_dir: "{{base_dir}}/edu-sharing_{{edu_version}}"
edu_home: "{{edu_inst_dir}}/edu-sharing"

edu_repo_caption: local-repo-vmtest
edu_repo_id: local

edu_client_config_xml_path: '{{ edu_home }}/war/WEB-INF/classes/org/edu_sharing/service/config/client.config.xml'

# the receiver address where to send mails
edu_mail_report_receiver:
# the encryption used to send mails, at the moment only "tls" or none (blank) is supported
edu_mail_authtype: tls
edu_mail_smtp_server:
# the credentials on the mail server needed to send mails, leave blank if not needed
edu_mail_smtp_username:
edu_mail_smtp_passwd:
# the mail server port
edu_mail_smtp_port: 25
# the sender address used to send mails
edu_mail_smtp_from: pleasechange@nodomain.com

edu_imprinturl:
edu_privacyInformationUrl:
# set to "true" to enable local registration of users
edu_register_local: "false"
edu_banner_url:
# set a href to enable Homebutton on banner image  e.g http://wwww.your-domain/edu-sharing/
edu_banner_href:
edu_banner_components:
  - search
# path to a custom banner that will be copied into the edu-sharing instance
edu_banner_path:
edu_logo_path:
# a list of custom images that should be copied into edu_sharing/assets/images; format of each entry: [<source-file-path>, <destination under edu_sharing/assets/images>]
# example: ['local/path/example.svg', 'example.svg']
edu_custom_images:
edu_mds_override_paths:
edu_valuespaces_paths:
edu_valuespaces_i18n_paths:
# a list of adjustments; format of each entry: [<i18n-file-path>, <KEY>, <NEW-VALUE>]
# example: ['common/de.json', 'USER_TUTORIAL_HEADING', 'Profil']
edu_i18n_adjustments:
# a list of additional help menu items; format of each entry: [<key>, <icon>, <url>]
edu_help_menu_options:
# a (string-)list of allowed licenses ("NONE","CC_0","CC_BY","SCHULFUNK","UNTERRICHTS_UND_LEHRMEDIEN","COPYRIGHT","CUSTOM")
edu_allowed_licenses:

edu_sharing_port:
edu_sharing_clientport:
edu_sharing_protocol: http
edu_sharing_clientprotocol:
  
edu_enable_statistics_api: "false"
