---
es_proxy_vhost: true

alf_installer_url: https://sourceforge.net/projects/alfresco/files/Alfresco%205.0.d%20Community/alfresco-community-5.0.d-installer-linux-x64.bin/download
alf_inst_dir: /opt
alf_home: "{{alf_inst_dir}}/alfresco-5.0.d"
alf_password: admin

java_inst_dir: "/opt"
java_home: "{{java_inst_dir}}/java"
tomcat_home: "{{alf_home}}/tomcat"
tomcat_port: 8080
tomcat_shutdown_port: 8005
tomcat_ssl_port: 8443
tomcat_ajp_port: 8009

edu_inst_dir: /opt
edu_home: "{{edu_inst_dir}}/edu-sharing"
edu_sharing_archive_url: https://github.com/edu-sharing/Edu-Sharing/releases/download/4.1.7/edu-sharing_4.1.7.2019-05-15-9ca4a3a2.zip
