# OnlyOffice variable

#onlyofficeor Version (Docker)
onlyoffice_version: latest
onlyoffice_jwt_enabled: true # true/false
onlyoffice_jwt_secret: "my_jwt_secret" # secret jwt token

# Database type for now supported only by postgres
# database configuration
onlyoffice_database:
  db_name: 'onlyoffice'
  db_user: 'onlyoffice'
  db_password: 'onlyoffice'


# Rabbit MQ Configuration
onlyoffice_rabbitmq_version:  latest
onlyoffice_rabbitmq_port:  5672
onlyoffice_rabbitmq_management_port:  15672
onlyoffice_rabbitmq_user: onlyoffice
onlyoffice_rabbitmq_pass: onlyoffice
onlyoffice_rabbitmq_vpath: /