---
esrender_vhost: true

esrender_version: 5.0.0
esrender_archive_url: 'https://github.com/edu-sharing/renderingservice/archive/{{esrender_version}}.tar.gz'
esrender_download_dir: "{{base_dir}}/esrender_{{esrender_version}}"
