---
esrender_vhost: true

esrender_version: 5.0.0
esrender_archive_url: 'https://github.com/edu-sharing/renderingservice/archive/{{esrender_version}}.tar.gz'
esrender_download_dir: "{{base_dir}}/esrender_{{esrender_version}}"

# remove existing renderingservice before new installation (true|false)
esrender_remove_existing: false
# download the renderingservice archive file every time, even if the file exists (yes|no)
esrender_force_download: no

# use http or cli to process install/update of renderingservice (cli|http)
# NOTE: currently (2020 July) there are errors in 'cli' mode with postgresql -> 'cli' works just with mariadb/mysql
esrender_exec_method: http

# method how to retrieve the esrender archive that should be installed
#  'download' - use the archive from 'esrender_archive_url'
#  'copy-local' - copy the archive from the local host in 'esrender_local_archive_path'
esrender_archive_retrieve_method: download
esrender_local_archive_path:

install_splash: false # install splash on renderingservice-hosts - see https://splash.readthedocs.io/en/stable/index.html

#  a list of configuration files for esrender
esrender_custom_config_files:
  # - ["config.php.j2","office/config.php"]