# TODO check embedded discovery service

# shibboleth installation enabled/disabled true|false
install_shibboleth: false

# Set your entityID here
shibboleth_sp_entity_id: "https://box.edusharing/shibboleth"
# Set your mail support address here
shibboleth_sp_support_contact: pleasechange@nodomain.com
# Set the location to your help html page here
shibboleth_sp_help_location: /contact.html
#shibboleth_sp_discovery_service_url: https://wayf.aai.dfn.de/DFN-AAI-Test/wayf # TEST
shibboleth_sp_discovery_service_url: https://wayf.aai.dfn.de/DFN-AAI-Basic/wayf # PROD
#shibboleth_sp_metadata_provider_url: http://www.aai.dfn.de/fileadmin/metadata/dfn-aai-test-metadata.xml # TEST
shibboleth_sp_metadata_provider_url: https://www.aai.dfn.de/fileadmin/metadata/dfn-aai-basic-metadata.xml # PROD
# Set the path to your (key and certificate) credential files.
# If you need to replace the existing credential files, you can
#   - add the new credentials at the end of the list
#   - wait 24h
#   - set the new credentials at the beginning of the list, set the old credentials at the end
#   - wait 24h
#   - remove the old credentials
# -> see https://doku.tid.dfn.de/de:certificates#zertifikatstausch
shibboleth_sp_credential_files:
  - certificate_file: /some/path/testcert.pem
    key_file: /some/path/test.key.pem
#  - certificate_file: /some/path/test2
#    key_file: /some/path/test2.key

# internal default variables - no need to set them
shibboleth_switchaai_apt_source_debian_stretch_package_url: https://pkg.switch.ch/switchaai/debian/dists/stretch/main/binary-all/misc/switchaai-apt-source_1.0.0~bpo9+1_all.deb
shibboleth_sp_protected_path: /edu-sharing/shibboleth     # path to edu-sharing shibboleth
shibboleth_sp_config_template: dfn-aai-shibboleth2.xml.j2 # the template that should be used for shibboleth2.xml
shibboleth_sp_attribute_map_file: attribute-map.xml       # the file that is used as /etc/shibboleth/attribute-map.xml
shibboleth_sp_error_css_file: shib-error.css              # stylesheet used for error pages
shibboleth_sp_metadata_provider_certificate: https://www.aai.dfn.de/fileadmin/metadata/dfn-aai.pem # DFN AAI certificate that should be used for validation of the metadata
