---
# need to downgrade java, because alfresco 5.2 cannot run out-of-the-box with later versions (problems with modularization in java 9)
java_name: zulu8.44.0.11-ca-jdk8.0.242-linux_x64
java_archive_url: 'https://cdn.azul.com/zulu/bin/{{java_name}}.tar.gz'

tomcat_version: '9.0.39'

java_inst_dir: "{{base_dir}}"
java_home: "{{java_inst_dir}}/java"

tomcat_inst_dir: "{{base_dir}}"
tomcat_bin: "{{tomcat_inst_dir}}/bin"
tomcat_home: "{{tomcat_inst_dir}}/tomcat"
tomcat_start_command: "nohup {{tomcat_bin}}/tomcat.sh start </dev/null >/dev/null 2>&1 &"
tomcat_stop_command: "{{tomcat_bin}}/tomcat.sh stop"
tomcat_log_dir: "{{ tomcat_inst_dir }}/log/tomcat" # if set, link tomcat-logs directory to this directory
