---
# need to downgrade java, because alfresco 5.2 cannot run out-of-the-box with later versions (problems with modularization in java 9)
java_name: zulu8.54.0.21-ca-jdk8.0.292-linux_x64
java_archive_url: 'https://cdn.azul.com/zulu/bin/{{java_name}}.tar.gz'

tomcat_version: '9.0.39'
tomcat_cleanup_logfiles: true # cleanup logfiles of tomcat true|false
tomcat_cleanup_cron_hour: '1'
tomcat_cleanup_cron_minute: '0'
logcompress_mtime: '+2' # default mtime value for file-compression (find command - see 'man find')
logdelete_mtime: '+20' # default mtime value for file-deletion (find command - see 'man find')

java_inst_dir: "{{base_dir}}"
java_home: "{{java_inst_dir}}/java"

tomcat_inst_dir: "{{base_dir}}"
tomcat_bin: "{{tomcat_inst_dir}}/bin"
tomcat_home: "{{tomcat_inst_dir}}/tomcat"
tomcat_start_command: "nohup {{tomcat_bin}}/tomcat.sh start </dev/null >/dev/null 2>&1 &"
tomcat_stop_command: "{{tomcat_bin}}/tomcat.sh stop"
tomcat_log_dir: "{{ tomcat_inst_dir }}/log/tomcat" # if set, link tomcat-logs directory to this directory

tomcat_connectors:
  - port: '{{ tomcat_port }}'
    protocol: 'HTTP/1.1'
    attributes:
      - 'connectionTimeout="20000"'
      - 'redirectPort="{{ tomcat_ssl_port }}"'
      - 'address="127.0.0.1"'
  - port: '{{ tomcat_ssl_port }}'
    protocol: 'org.apache.coyote.http11.Http11NioProtocol'
    attributes:
      - 'URIEncoding="UTF-8"'
      - 'SSLEnabled="true"'
      - 'maxThreads="150"'
      - 'scheme="https"'
      - 'keystoreFile="{{ alf_home }}/alf_data/keystore/ssl.keystore"'
      - 'keystorePass="kT9X6oe68t"'
      - 'keystoreType="JCEKS"'
      - 'secure="true"'
      - 'connectionTimeout="240000"'
      - 'truststoreFile="{{ alf_home }}/alf_data/keystore/ssl.truststore"'
      - 'truststorePass="kT9X6oe68t"'
      - 'truststoreType="JCEKS"'
      - 'clientAuth="optionalNoCA"'
      - 'sslProtocol="TLS"'
      - 'allowUnsafeLegacyRenegotiation="true"'
      - 'maxHttpHeaderSize="32768"'
      - 'address="127.0.0.1"'
  - port: '{{ tomcat_ajp_port }}'
    protocol: 'AJP/1.3'
    attributes:
      - 'redirectPort="{{ tomcat_ssl_port }}"'
      - 'secretRequired="false"'
      - 'allowedRequestAttributesPattern=".*"'
      - 'tomcatAuthentication="false"'
      - 'address="127.0.0.1"'
