---
- name: Get the path to the edu-sharing config docker volume.
  shell: 'sg docker -c "docker volume inspect --format ''{{ ''{{'' }}.Mountpoint{{ ''}}'' }}''  $(docker volume ls -q |grep ''_repository-service-volume-config-node'')" '
  register: edu_sharing_client_xml_path
  tags:
    - edu-sharing-config
    - edu-sharing-docker-config


- include: ./common/client-configuration.yml
    client_configuration_path='{{edu_sharing_client_xml_path.stdout}}/defaults/client.config.xml'
  become: yes
  when: edu_sharing_client_xml_path.stdout is defined and edu_sharing_client_xml_path.stdout != ""
  tags:
    - edu-sharing-config
    - edu-sharing-docker-config

- include: ./common/metadatasets.yml
    metadatasets_directory_path='{{edu_sharing_client_xml_path.stdout}}/defaults/metadatasets'
  become: yes
  when: edu_sharing_client_xml_path.stdout is defined and edu_sharing_client_xml_path.stdout != ""
  tags:
    - edu-sharing-config
    - edu-sharing-docker-config

- include: custom-menu-entries.yml
    custom_menu_entries_path='{{edu_sharing_client_xml_path.stdout}}'
  become: yes
  when: ( edu_sharing_client_xml_path.stdout is defined and edu_sharing_client_xml_path.stdout != "")        
  tags:
    - edu-sharing-config
    - edu-sharing-docker-config
    - custom-menu-entries

- include: ./common/hide_main_menu.yml
    hide_main_menu_config_xml_path='{{edu_sharing_client_xml_path.stdout}}/defaults/client.config.xml'
  become: yes
  when: edu_sharing_client_xml_path.stdout is defined and edu_sharing_client_xml_path.stdout != ""
  tags:
    - edu-sharing-config
    - edu-sharing-docker-config
    - hide-main-menu