---
- name: Get the path to the Edu-sharing assets docker volume.
  shell: |
    sg docker -c "docker volume inspect --format '{{ '{{' }}.Mountpoint{{ '}}' }}'  $(sg docker -c "docker volume ls -q |grep '_repository-service-volume-config-edu-sharing'")"
  register: edu_sharing_assets_path
  ignore_errors: true
  tags:
    - edu-sharing-config

- include: ./common/images.yml
    edu_sharing_images_path="{{edu_sharing_assets_path.stdout}}"
  become: yes
  when: (edu_sharing_assets_path.stdout is defined) and (edu_sharing_assets_path.stdout != "")
  tags:
    - edu-sharing-config
    - images

- include: ./common/editI18n.yml
    i18n_path="{{edu_sharing_assets_path.stdout}}/assets/i18n"
  become: yes
  when: (edu_sharing_assets_path.stdout is defined) and (edu_sharing_assets_path.stdout != "")
  tags:
    - edu-sharing-config
    - i18n
