---
- name: Get the path to the edu-sharing cluster docker volume.
  shell: |
    sg docker -c "docker volume inspect --format '{{ '{{' }}.Mountpoint{{ '}}' }}'  $(sg docker -c "docker volume ls -q |grep '_repository-service-volume-config-cluster'")"
  register: repository_volume_config_cluster
  ignore_errors: true
  tags:
    - edu-sharing-config

- include: ./common/edu-sharing-config-file.yml
    edu_sharing_config_file_path='{{repository_volume_config_cluster.stdout}}/edu-sharing.override.conf'
  become: yes
  when: (repository_volume_config_cluster.stdout is defined) and (repository_volume_config_cluster.stdout != "")
  tags:
    - edu-sharing-config

- include: ./common/youtube.yml
    youtube_path='{{repository_volume_config_cluster.stdout}}/applications'
  become: yes
  when: connect_content_youtube and
    (repository_volume_config_cluster.stdout is defined) and (repository_volume_config_cluster.stdout != "")
  tags:
    - edu-sharing-config
    - youtube

- include: ./common/pixabay.yml
    pixabay_path='{{repository_volume_config_cluster.stdout}}/applications'
  become: yes
  when: connect_content_pixabay and
    (repository_volume_config_cluster.stdout is defined) and (repository_volume_config_cluster.stdout != "")
  tags:
    - edu-sharing-config
    - pixabay

- include: ./common/lms.yml
    lms_path='{{repository_volume_config_cluster.stdout}}/applications'
  become: yes
  when: (repository_volume_config_cluster.stdout is defined) and (repository_volume_config_cluster.stdout != "")
  tags:
    - edu-sharing-config
    - lms

- include: ./common/shibboleth_after.yml
    shibboleth_after_path='{{repository_volume_config_cluster.stdout}}/applications'
  become: yes
  when: (edu_configure_shibboleth is defined and edu_configure_shibboleth) and
        (repository_volume_config_cluster.stdout is defined) and (repository_volume_config_cluster.stdout != "")
  tags:
    - edu-sharing-config
    - shibboleth
