---

- name: Get the path to the edu-sharing cluster docker volume.
  shell: | 
    sg docker -c "docker volume inspect --format '{{ '{{' }}.Mountpoint{{ '}}' }}'  $(docker volume ls -q |grep '_repository-service-volume-config-cluster')"
  register: repository_volume_config_cluster
  ignore_errors: true
  tags:
  - edu-sharing-config

- name: Copy edu-sharing.conf to Edu-sharing cluster volume.
  become: yes
  template:
    src: edu-sharing.conf.j2
    dest: "{{repository_volume_config_cluster.stdout}}/edu-sharing.override.conf"
    mode: '775'
  when: repository_volume_config_cluster.stdout != "" and  edu_config_file == 'edu-sharing.conf'
  tags: edu-sharing-config

- include: youtube.yml
  become: yes
  vars:
    youtube_path: '{{repository_volume_config_cluster.stdout}}'
  when: connect_content_youtube and repository_volume_config_cluster.stdout != ""
  tags:
    - edu-sharing-config
    - youtube

- include: pixabay.yml
  become: yes
  vars: 
    pixabay_path: '{{repository_volume_config_cluster.stdout}}'
  when: connect_content_pixabay and repository_volume_config_cluster.stdout != ""
  tags:
    - edu-sharing-config
    - pixabay

- include: lms.yml
  become: yes
  vars:
    lms_path: '{{repository_volume_config_cluster.stdout}}'
  when: repository_volume_config_cluster.stdout != ""
  tags:
    - edu-sharing-config
    - lms

- name: Restart edu-sharing.
  command:
    chdir: '{{ edu_inst_dir }}'
    cmd: '{{edu_sharing_deploy_command}}'
  no_log: true
  tags: edu-sharing-config