---
# Include the es-update-oersi amp file
- include: ./common/es_update_oersi.yml
    es_amp_destination='{{ edu_docker_inst_dir }}/custom-repository-service/esupdate/'


- name: modify reinstall.sh script to accept alfviral amp
  blockinfile:
    path: "{{ edu_docker_inst_dir }}/custom-repository-service/reinstall.sh"
    insertbefore: "^libcheck.sh$"
    marker: "# Add es-update-oersi amp file"
    block: |
        if [[ -d amps/esupdate ]] ; then
          java -jar bin/alfresco-mmt.jar install amps/esupdate tomcat/webapps/alfresco -directory -nobackup -force
        fi