---

- name: Get the path to the alfresco config docker volume.
  shell: "sg docker -c \"docker volume inspect --format '{{ '{{' }}.Mountpoint{{ '}}' }}'  $(docker volume ls -q |grep '_repository-service-volume-config-node')\" "
  register: edu_sharing_metadata_path
  ignore_errors: true
  tags:
  - edu-sharing-config

- name: Copy mds_override.xml.
  become: yes
  copy:
    src: '{{item}}'
    dest: '{{edu_sharing_metadata_path.stdout}}/defaults/metadatasets/xml'
    mode: '775'
  when: (edu_mds_override_paths is defined) and (edu_mds_override_paths != "") and 
        (edu_mds_override_paths is not none) and edu_sharing_metadata_path.stdout != ""
  with_items: '{{edu_mds_override_paths}}'
  tags:
  - edu-sharing-config

- name: Copy valuespaces.
  become: yes
  copy:
    src: '{{item}}'
    dest: '{{edu_sharing_metadata_path.stdout}}/defaults/metadatasets/xml/valuespaces/'
    mode: '775'
  when: (edu_valuespaces_paths is defined) and (edu_valuespaces_paths != "") and 
        (edu_valuespaces_paths is not none) and edu_sharing_metadata_path.stdout != ""
  with_items: '{{edu_valuespaces_paths}}'
  tags:
  - edu-sharing-config

- name: Copy i18n.
  become: yes
  copy:
    src: '{{item}}'
    dest: '{{edu_sharing_metadata_path.stdout}}/defaults/metadatasets/i18n/'
    mode: '775'
  when: (edu_valuespaces_i18n_paths is defined) and (edu_valuespaces_i18n_paths != "") and 
        (edu_valuespaces_i18n_paths is not none) and edu_sharing_metadata_path.stdout != ""
  with_items: '{{edu_valuespaces_i18n_paths}}'
  tags:
  - edu-sharing-config