---
- name: Check if alfresco alf_data exists
  find:
    paths: "{{alf_home}}/alf_data"
    file_type: any
    # hidden: true
  register: alfresco_alf_data_exist
  tags: migrate-edu-sharing

# check only postgres database, since edu-sharing docker version is not available for mariadb
- name: Check if alfresco database exists.
  postgresql_ping:
    db: "{{alfresco_db.name}}"
    login_host: localhost
    login_user: "{{alfresco_db.user}}"
    login_password: "{{alfresco_db.password}}"
  register: exist_alfresco_database
  ignore_errors: yes
  when: alfresco_db_type == 'postgresql'
  tags: migrate-edu-sharing

- name: Purge all docker images and containers.
  shell: "{{edu_sharing_purge_all_command}}"
  args:
    chdir: "{{edu_docker_inst_dir}}/"
  when:
    (alfresco_alf_data_exist is defined and alfresco_alf_data_exist.matched > 0) and
    (exist_alfresco_database.is_available is defined and exist_alfresco_database.is_available|bool)
  tags: migrate-edu-sharing

- include: migrate-alfresco-data.yml
  when:
    (alfresco_alf_data_exist is defined and alfresco_alf_data_exist.matched > 0) and
    (exist_alfresco_database.is_available is defined and exist_alfresco_database.is_available|bool)
  tags: migrate-edu-sharing
