---
  - set_fact: edu_docker_inst_dir="{{ edu_inst_dir|replace('.','_') }}" 
    tags:
      - edu-sharing-customization

  - name: Ensure the java_home variable is set.
    include_role:
      name: java
      tasks_from: get_java_home
      apply:
        tags:
          - edu-sharing-customization
    when:  java_home is not defined
    tags:
      - edu-sharing-customization

  - include_role:
      name: edu-sharing-init
      tasks_from: load_version_variables
      apply:
        tags:
          - edu-sharing-customization
    tags:
      - edu-sharing-customization
    

  - name: Ensure gzip and jq python-lxml are present.
    package:
      name:
        - unzip
        - jq
        - gzip
        - python3-lxml
    become: true
    tags:
      - edu-sharing-customization

  - include_tasks: adjust_env_variables.yml
    tags:
      - edu-sharing-customization

  - include_tasks: ./config-cluster/main.yml
    tags:
      - edu-sharing-customization
  - include_tasks: ./config-edu-sharing/main.yml
    tags:
      - edu-sharing-customization
  - include_tasks: ./config-node/main.yml
    tags:
      - edu-sharing-customization

  - include_tasks: shibboleth_before.yml
    args:
      apply:
        become: yes
    vars:
      shibboleth_before_client_config_path: '{{repository_volume_config_node_path.stdout}}/defaults/client.config.xml'
      edu_sharing_webapp_webinf_classes_path: '{{ repository_config_edu_sharing_path.stdout }}/WEB-INF/classes'
      edu_sharing_webapp_lib_path: '{{ repository_config_edu_sharing_path.stdout }}/WEB-INF/lib'
    when: (edu_configure_shibboleth is defined and edu_configure_shibboleth) and
          (repository_volume_config_node_path.stdout is defined) and (repository_volume_config_node_path.stdout != "") and
          (repository_volume_config_node_path.stdout is defined and repository_volume_config_node_path.stdout != "")
    tags:
      - edu-sharing-customization
      - edu-sharing-customization-shibboleth-before

  - name: Restart edu-sharing service in docker.
    command:
      chdir: "{{ edu_docker_inst_dir }}"
      cmd: "{{edu_sharing_restart_command | replace('{service}', 'repository-service')}}"
    # no_log: true
    tags:
      - edu-sharing-customization

  - include_tasks: jobs.yml
    tags:
      - edu-sharing-customization
      - edu-sharing-customization-jobs