---

# (internal) cleanup / set values in client.config.xml
# format:
#   xpath   - xpath where to set the value
#   value   - xml value
#   cleanup - xpath. if set, remove from client.config.xml before set values
edu_client_config_xml_standard_entries:
  - xpath: '/config/values/imprintUrl'
    value: '{{ edu_imprinturl | default("") }}'
  - xpath: '/config/values/privacyInformationUrl'
    value: '{{ edu_privacyInformationUrl | default("") }}'
  - xpath: '/config/values/register/local'
    value: '{{ edu_register_local }}'
  - xpath: '/config/values/register/recoverUrl'
    value: '{{ edu_recover_url }}'
    cleanup: '/config/values/register/recoverUrl'
  - xpath: '/config/values/banner/url'
    value: '{{ edu_banner_url | default("") }}'
    cleanup: '/config/values/banner'
  - xpath: '/config/values/banner/href'
    value: '{{ edu_banner_href | default("") }}'
    cleanup: '/config/values/banner'
  - cleanup: '/config/values/allowedLicenses'
  - cleanup: '/config/values/loginUrl'
  - cleanup: '/config/values/loginAllowLocal'
  - cleanup: '/config/values/loginProvidersUrl'
  - cleanup: '/config/values/loginProviderTargetUrl'
  - cleanup: '/config/values/logout'
  - xpath: '/config/values/workspaceViewType'
    value: '{{ "1" if (edu_workspace_viewType | default("list")) == "tile" else "0" }}'
    cleanup: '/config/values/workspaceViewType'
  - xpath: '/config/values/upload/postDialog'
    value: '{{ edu_upload_post_dialog }}'

# path of the client.config.xml (edu_version < 5.1: '{{ edu_home }}/war/WEB-INF/classes/org/edu_sharing/service/config/client.config.xml' and edu_version >= 5.1: '{{ edu_home }}/config/client.config.xml')
edu_client_config_xml_path: '{{ edu_home }}/config/client.config.xml'

edu_sharing_workaround_jar_cleanup: [] # sometimes there are jar-conflicts that causes errors in some tomcat versions -> workaround removes invalid jars (depending on the edu-sharing version), root-dir is tomcat-webapps-dir

# edu-sharing configuration type (edu_version < 5.1: 'edu-sharing.properties' and edu_version >= 5.1: 'edu-sharing.conf'
edu_config_file: 'edu-sharing.conf'

# trusted client configuration for oauthTokenService
edu_oauth_trusted_clients:
  - client: "eduApp"
    password: "secret"

mirror_vocabs_hour: "4"

oersi_caption: "Überregionale Suche"
oersi_host: "oersi.de"
oersi_port: "443"
oersi_scheme: "https"
oersi_pathprefix: "/resources/api-internal/search"
oersi_index: "oer_data"

# Default values for classifications keywords
# define the classification-keyword interval in days = 1 means every day
classification_keywords_update_interval: 15
# give the path to the file where you want download the classification-keywords
# must be public folder: example: /var/www/oer/
classification_keywords_dir: "classification-keywords"
#  classification keywords base dir
classification_keywords_base_dir: "/var/www/{{classification_keywords_dir}}"
# define the classification-keyword file name example: classification_keywords.xml
classification_keywords_file: "classification_keywords.xml"
# Classification-Keywords-URL (for download)
classification_keywords_url: "https://data.dnb.de/GND/authorities-sachbegriff_dnbmarc_20211013.mrc.xml.gz"
# classification-keywords initial by job
classification_keywords_job:
    jobClass: "org.edu_sharing.repository.server.jobs.quartz.ImportFactualTermMarc21"
    params:
       fileUri: '{{ edu_sharing_protocol | default("http") }}://{{edu_sharing_host}}/{{classification_keywords_dir}}/{{classification_keywords_file}}'