---

# (internal) cleanup / set values in client.config.xml
# format:
#   xpath   - xpath where to set the value
#   value   - xml value
#   cleanup - xpath. if set, remove from client.config.xml before set values
edu_client_config_xml_standard_entries:
  - xpath: '/config/values/imprintUrl'
    value: '{{ edu_imprinturl | default("") }}'
  - xpath: '/config/values/privacyInformationUrl'
    value: '{{ edu_privacyInformationUrl | default("") }}'
  - xpath: '/config/values/register/local'
    value: '{{ edu_register_local }}'
  - xpath: '/config/values/register/recoverUrl'
    value: '{{ edu_recover_url }}'
    cleanup: '/config/values/register/recoverUrl'
  - xpath: '/config/values/banner/url'
    value: '{{ edu_banner_url | default("") }}'
    cleanup: '/config/values/banner'
  - xpath: '/config/values/banner/href'
    value: '{{ edu_banner_href | default("") }}'
    cleanup: '/config/values/banner'
  - cleanup: '/config/values/allowedLicenses'
  - cleanup: '/config/values/loginUrl'
  - cleanup: '/config/values/loginAllowLocal'
  - cleanup: '/config/values/loginProvidersUrl'
  - cleanup: '/config/values/loginProviderTargetUrl'
  - cleanup: '/config/values/logout'
  - xpath: '/config/values/workspaceViewType'
    value: '{{ "1" if (edu_workspace_viewType | default("list")) == "tile" else "0" }}'
    cleanup: '/config/values/workspaceViewType'
  - xpath: '/config/values/upload/postDialog'
    value: '{{ edu_upload_post_dialog }}'
  - xpath: '/config/values/publish/licenseMandatory'
    value: '{{ edu_license_mandatory | default(false) }}'
    cleanup: '/config/values/publish/licenseMandatory'
  - xpath: '/config/values/publish/authorMandatory'
    value: '{{ edu_author_mandatory | default(false) }}'
    cleanup: '/config/values/publish/authorMandatory'

# path of the client.config.xml (edu_version < 5.1: '{{ edu_home }}/war/WEB-INF/classes/org/edu_sharing/service/config/client.config.xml' and edu_version >= 5.1: '{{ edu_home }}/config/client.config.xml')
edu_client_config_xml_path: '{{ edu_home }}/config/client.config.xml'

edu_sharing_workaround_jar_cleanup: [] # sometimes there are jar-conflicts that causes errors in some tomcat versions -> workaround removes invalid jars (depending on the edu-sharing version), root-dir is tomcat-webapps-dir

# edu-sharing configuration type (edu_version < 5.1: 'edu-sharing.properties' and edu_version >= 5.1: 'edu-sharing.conf'
edu_config_file: 'edu-sharing.conf'

# trusted client configuration for oauthTokenService
edu_oauth_trusted_clients:
  - client: "eduApp"
    password: "secret"

mirror_vocabs_hour: "4"

oersi_caption: "Überregionale Suche"
oersi_host: "oersi.org"
oersi_port: "443"
oersi_scheme: "https"
oersi_pathprefix: "/resources/api-internal/search"
oersi_index: "oer_data"


edu_sharing_docker_project_name: "edu_sharing_docker_version"
edu_sharing_docker_timezone: '{{timezone | default("Europe/Berlin",true)}}'

edu_sharing_environment_variable:
  - key: COMPOSE_PROJECT_NAME
    value: '{{edu_sharing_docker_project_name}}'
  - key: REPOSITORY_DATABASE_NAME
    value: '{{alfresco_db.name}}'
  - key: REPOSITORY_DATABASE_USER
    value: '{{alfresco_db.user}}'
  - key: REPOSITORY_DATABASE_PASS
    value: '{{alfresco_db.password}}'
  - key: COMMON_BIND_HOST
    value: '127.0.0.1'
  - key: REPOSITORY_SERVICE_PORT
    value: '{{edu_sharing_port | default("80",true)}}'
  - key: SERVICES_RENDERING_SERVICE_PORT
    value: '{{edu_sharing_port | default("80",true)}}'
  - key: REPOSITORY_SERVICE_GUEST_USER
    value: 'esguest'
  - key: REPOSITORY_SERVICE_GUEST_PASS
    value: 'esguest'
  - key: REPOSITORY_SERVICE_ADMIN_PASS
    value: '{{alf_password}}'
  - key: SERVICES_RENDERING_SERVICE_HOST
    value: '{{edu_sharing_host}}'
  - key: SERVICES_RENDERING_DATABASE_NAME
    value: '{{esrender_db.name}}'
  - key: SERVICES_RENDERING_DATABASE_USER
    value: '{{esrender_db.user}}'
  - key: SERVICES_RENDERING_DATABASE_PASS
    value: '{{esrender_db.password}}'
  - key: REPOSITORY_SERVICE_HOST
    value: '{{edu_sharing_host}}'
  - key: SERVICES_RENDERING_SERVICE_HOST
    value: '{{edu_sharing_host}}'
  - key: REPOSITORY_SERVICE_MAIL_SERVER_SMTP_PORT
    value: '{{edu_mail_smtp_port if (edu_mail_smtp_server is not none) and (edu_mail_smtp_server is defined) else ""}}'
  - key: REPOSITORY_SERVICE_MAIL_FROM
    value: '{{edu_mail_smtp_from if (edu_mail_smtp_server is not none) and (edu_mail_smtp_server is defined) else ""}}'
  - key: REPOSITORY_SERVICE_MAIL_REPORT_RECEIVER
    value: '{{edu_mail_report_receiver if (edu_mail_smtp_server is not none) and (edu_mail_smtp_server is defined) else ""}}'
  - key: REPOSITORY_SERVICE_MAIL_SERVER_SMTP_USERNAME
    value: '{{edu_mail_smtp_username if (edu_mail_smtp_server is not none) and (edu_mail_smtp_server is defined) else ""}}'
  - key: REPOSITORY_SERVICE_MAIL_SERVER_SMTP_PASSWORD
    value: '{{edu_mail_smtp_passwd if (edu_mail_smtp_server is not none) and (edu_mail_smtp_server is defined) else ""}}'
  - key: REPOSITORY_SERVICE_MAIL_SERVER_SMTP_AUTHTYPE
    value: '{{edu_mail_authtype if (edu_mail_smtp_server is not none) and (edu_mail_smtp_server is defined) else ""}}'
  - key: REPOSITORY_SERVICE_MAIL_SERVER_SMTP_HOST
    value: '{{edu_mail_smtp_server | default("",true)}}'
  - key: REPOSITORY_SERVICE_HOME_APPID
    value: '{{edu_repo_id | default("local",true)}}'
  - key: REPOSITORY_SERVICE_AUTH_EXTERNAL
    value: '{{ "true" if (edu_configure_shibboleth is defined) and (edu_configure_shibboleth)  else ""}}'
  - key: REPOSITORY_SERVICE_AUTH
    value: '{{ "shibboleth" if (edu_configure_shibboleth is defined) and (edu_configure_shibboleth)  else ""}}'
  - key: REPOSITORY_SERVICE_AUTH_EXTERNAL_LOGIN
    value: '{{ "/edu-sharing/shibboleth" if (edu_configure_shibboleth is defined) and (edu_configure_shibboleth)  else ""}}'
  - key: REPOSITORY_SERVICE_AUTH_EXTERNAL_LOGOUT
    value: '{{ shibboleth_sp_base_path +"/Shibboleth.sso/Logout?return=" +  edu_sharing_url + "/components/login" if (edu_configure_shibboleth is defined) and (edu_configure_shibboleth)  else ""}}'

mail_configuration:
  - key: mail.host
    value: "{{ edu_mail_smtp_server | default('') }}"
  - key: mail.port
    value: '{{ edu_mail_smtp_port | default("25") }}'
  - key: mail.username
    value: '{{ edu_mail_smtp_username | default("") }}'
  - key: mail.password
    value: '{{ edu_mail_smtp_passwd | default("") }}'
  - key: mail.encoding
    value: '{{ edu_mail_smtp_encoding | default("UTF-8",true) }}'
  - key: mail.from.default
    value: '{{ edu_mail_smtp_from | default("pleasechange@nodomain.com") }}'
  - key: mail.smtp.auth
    value: '{{ edu_mail_smtp_auth | default("false") }}'

alfviral_antivirus_configuration:
  - key: alfviral.mode
    value: "INSTREAM"
  - key: alfviral.instream.timeout
    value: "{{antivirus_alfviral_timeout | default(10000,true)}}"
  - key: alfviral.instream.host
    value: "{{clamav_proxy}}"
  - key: alfviral.instream.port
    value: "{{antivirus_alfviral_port | default(3310,true)}}"
  - key: alfviral.on_update.delete
    value: "{{ antivirus_alfviral_on_update_delete | default('true',true) }}"
  - key: alfviral.notify.user
    value: "{{ antivirus_alfviral_notify_user | default('true',true)}}"
  - key: alfviral.notify.admin
    value: "{{ antivirus_alfviral_notify_admin | default('true',true)}}"
  - key: alfviral.notify.asynchronously
    value: "{{ antivirus_alfviral_notify_asynchronously | default('false',true) }}"
  - key: alfviral.notify.user.template
    value: "{{ antivirus_alfviral_user_template | default('notify_user_en.html.ftl',true) }}"
  - key: alfviral.notify.admin.template
    value: "{{ antivirus_alfviral_admin_template | default('notify_admin_en.html.ftl',true) }}"
  - key: alfviral.file.exceptions
    value: ""

es_update_oersi_amp_filename: "es-update-oersi-{{es_update_oersi_version}}.amp"
es_update_oersi_configuration:
  - key: oersi.url
    value: "{{es_update_oersi_url | default('',true)}}"
  - key: edu_sharing.baseUrl
    value: "{{edu_sharing_url | default('',true)}}"