---
- name: Ensures backup_path dir exists
  file: path='{{ backup_path }}' state=directory
  tags:
    - edu-sharing-backup

- set_fact: edu_docker_inst_dir="{{ edu_inst_dir|replace('.','_')}}"
  tags:
    - edu-sharing-backup

- include_role:
    name: edu-sharing-init
    tasks_from: load_version_variables
    apply:
      tags:
        - edu-sharing-backup
  tags:
    - edu-sharing-backup

- include_tasks: backup.yml
  tags: 
    - edu-sharing-backup

