---
- name: undeploy alresco war-files from tomcat
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{tomcat_home}}/webapps/alfresco.war"
    - "{{tomcat_home}}/webapps/share.war"

- name: wait for war-file-undeployment
  wait_for:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{tomcat_home}}/webapps/alfresco/"
    - "{{tomcat_home}}/webapps/share/"

- name: download mysql jconnector (mariadb driver not supported by alfresco)
  get_url:
    url: '{{mysql_jconnector_url}}'
    dest: "{{tomcat_home}}/lib/mysql-connector-java.jar"
    force: yes # necessary for driver updates
  when: alfresco_db_type == 'mariadb'

- name: download postgres jconnector
  get_url:
    url: '{{postgresql_jconnector_url}}'
    dest: "{{tomcat_home}}/lib/postgresql.jar"
    force: yes # necessary for driver updates
  when: alfresco_db_type == 'postgresql'

- name: download alfresco sources
  get_url:
    url: '{{alf_sources_url}}'
    dest: "{{alf_inst_dir}}/{{alf_name}}.zip"

- name: Ensure unzip is present
  package:
    name: ["unzip"]
  become: yes
  tags:
  - packages
  - root-task

- name: extract alfresco sources
  unarchive:
    remote_src: yes
    src: '{{alf_inst_dir}}/{{alf_name}}.zip'
    dest: "{{alf_inst_dir}}"
    creates: "{{alf_home}}"

- name: copy alresco war-files to tomcat
  copy:
    src: "{{item}}"
    dest: "{{tomcat_home}}/webapps"
    remote_src: yes
  with_items:
    - "{{alf_home}}/web-server/webapps/alfresco.war"
    - "{{alf_home}}/web-server/webapps/share.war"

- name: Ensures {{tomcat_home}}/shared dir exists
  file: path={{tomcat_home}}/shared/ state=directory

- name: copy alresco default tomcat config
  copy:
    src: "{{alf_home}}/web-server/shared/classes"
    dest: "{{tomcat_home}}/shared/"
    remote_src: yes

- name: activate shared.loader for tomcat
  lineinfile:
    path: '{{ tomcat_home }}/conf/catalina.properties'
    line: 'shared.loader=${catalina.base}/shared/classes'
    regexp: 'shared.loader='

- name: Configure alfresco-global.properties
  template:
    src: alfresco-global.properties.j2
    dest: '{{tomcat_home}}/shared/classes/alfresco-global.properties'

- name: Ensure python-lxml packages are present
  apt:
    name: ["python-lxml"]
  become: yes
  tags:
  - packages
  - root-task

- name: modify tomcat config - allow only local access
  xml:
    path: '{{tomcat_home}}/conf/server.xml'
    xpath: /Server/Service/Connector
    attribute: address
    value: 127.0.0.1
