---

  - name: Ensure tomcat is stopped.
    shell: '{{tomcat_stop_command}}'
    tags:
    - backup-alfresco-data

  - name: Ensures backup_path dir exists
    file: path='{{ backup_path }}' state=directory
    tags:
    - backup-alfresco-data

  - name: backup alfresco database 
    no_log: true
    shell: |
      PGPASSWORD="{{alfresco_db.password}}" pg_dump -h localhost -U {{alfresco_db.user}}  {{alfresco_db.name}}  --serializable-deferrable | gzip > {{backup_path}}/{{alfresco_db.name}}-dump.sql.gz
    tags:
    - backup-alfresco-data

  - name: create backup directory for alfresco data.
    archive:
      path: "{{ alf_home}}/alf_data/*"
      dest: "{{ backup_path }}/alfresco-backup.tar.gz"
      format: gz
    tags:
    - migration-alfresco-data

  - name: Ensure tomcat is stopped.
    shell: '{{tomcat_start_command}}'
    tags:
    - backup-alfresco-data