---
- name: Add custom menu entry Block
  block:
    #  add custom menu entry
    - name: add custom menu entry to client.config.xml
      xml:
        path: '{{ edu_client_config_xml_path }}'
        xpath: '/config/values'
        add_children: > 
            <menuEntries>
              <name>{{custom_menu_entry.name|upper }}</name>
              <scope>{{custom_menu_entry.scope | lower | default('workspace', true)}}</scope>
              <icon>{{custom_menu_entry.icon | default('open_in_new', true)}}</icon>
              <position>{{custom_menu_entry.position | default(-1, true)}}</position>
              <openInNew>{{custom_menu_entry.openInNew | default('false', true)}}</openInNew>
              {% if custom_menu_entry.url is defined %}
              <url>{{custom_menu_entry.url}}</url>
              {% endif %}
              {% if custom_menu_entry.path is defined %}
              <path>{{custom_menu_entry.path}}</path>
              {% endif %}
              <isSeperate>{{custom_menu_entry.isSeperate | default('false', true)}}</isSeperate>
              <isDisabled>{{custom_menu_entry.isDisabled | default('false', true)}}</isDisabled>
              <onlyDesktop>{{custom_menu_entry.onlyDesktop | default('false', true)}}</onlyDesktop>
              <onlyWeb>{{custom_menu_entry.onlyWeb | default('false', true)}}</onlyWeb>
            </menuEntries>
        input_type: xml
        pretty_print: yes
      when: custom_menu_entry is not none
      tags: edu-sharing-config

    # let's add/update the Key,value for custom menu entry in ../common/en.json file
    - name: set custom menu entry labels to ../common/[langCode].json
      # become: yes
      shell: | 
        jq '.{{custom_menu_entry.name|upper }} ="{{item[1]}}"' \
        {{ edu_home }}/war/edu_sharing/assets/i18n/common/{{item[0]}}.json >tmp.json && mv tmp.json {{ edu_home }}/war/edu_sharing/assets/i18n/common/{{item[0]}}.json
      when: custom_menu_entry.name is match('SIDEBAR.*')
      loop: '{{ custom_menu_entry.labels | default([], true) }}'
      tags: edu-sharing-config

  # since custom menu entry is not a mandatory,in order to make edu-sharing working, we don't want to stop the ansible,
  # we want to let ansible continue, and just remove the current custom menu entry
  rescue:
  - name: It caught an error, we will rollback last insert, from client.config.xml
    xml:
      path: '{{ edu_client_config_xml_path }}'
      xpath: "/config/values/menuEntries[id='{{custom_menu_entry.name|upper }}']"
      state: absent
      pretty_print: yes
    tags: edu-sharing-config

  - name: it caught an error, we will rollback last insert, from ../common/[en/de].json
    shell: | 
      jq 'del(.SIDEBAR.{{custom_menu_entry.name|upper }})' \
      {{ edu_home }}/war/edu_sharing/assets/i18n/common/{{item[0]}}.json >tmp.json && mv tmp.json {{ edu_home }}/war/edu_sharing/assets/i18n/common/{{item[0]}}.json
    loop: '{{ custom_menu_entry.labels | default([], true) }}'
    tags: edu-sharing-config

