---
- name: stop alfresco
  shell: '{{tomcat_stop_command}}'

- name: Ensures inst-dir exists
  file: path='{{edu_inst_dir}}' state=directory

- name: download edu-sharing sources
  get_url:
    url: '{{edu_sharing_archive_url}}'
    dest: "{{edu_inst_dir}}/edu-sharing.zip"

- name: Ensure unzip is present
  package:
    name: ["unzip"]
  become: yes
  tags:
  - packages
  - root-task

- name: extract edu-sharing sources
  unarchive:
    remote_src: yes
    src: '{{edu_inst_dir}}/edu-sharing.zip'
    dest: "{{edu_inst_dir}}"
    creates: "{{edu_home}}"

- name: edit edu-sharing build.properties
  lineinfile:
    path: '{{ edu_home }}/build.properties'
    line: 'webserver.home={{tomcat_home}}'
    regexp: '^webserver.home=.*$'

- name: edit edu-sharing call-ant.sh
  replace:
    path: '{{ edu_home }}/call-ant.sh'
    replace: '{{java_home}}/bin/java '
    regexp: '^java '

- name: edit edu-sharing call-ant.sh
  replace:
    path: '{{ edu_home }}/call-ant.sh'
    replace: '-classpath '
    regexp: '-Djava.ext.dirs='

- name: make edu-sharing install.sh executable
  file:
    path: '{{ edu_home }}/install.sh'
    mode: 'a+x'

- name: run edu-sharing install.sh
  shell: '{{ edu_home }}/install.sh'
  args:
    chdir: '{{ edu_home }}'

- name: edit password in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ tomcat_home }}/shared/classes/homeApplication.properties.xml'
    line: '<entry key="password">{{alf_password}}</entry>'
    regexp: '<entry key="password">'

- name: edit host in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ tomcat_home }}/shared/classes/homeApplication.properties.xml'
    line: '<entry key="host">{{edu_sharing_host}}</entry>'
    regexp: '<entry key="host">'

- name: edit domain in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ tomcat_home }}/shared/classes/homeApplication.properties.xml'
    line: '<entry key="domain">{{edu_sharing_domain}}</entry>'
    regexp: '<entry key="domain">'

- name: edit port in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ tomcat_home }}/shared/classes/homeApplication.properties.xml'
    line: '<entry key="port">80</entry>'
    regexp: '<entry key="port">'

- name: edit port in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ tomcat_home }}/shared/classes/homeApplication.properties.xml'
    line: '<entry key="clientport">80</entry>'
    regexp: '<entry key="clientport">'

- name: start alfresco
  shell: '{{tomcat_start_command}}'
