---
  - include: mariadb.yml
    when: alfresco_db_type == 'mariadb'
  - include: postgresql.yml
    when: alfresco_db_type == 'postgresql'
    tags:
      - backup
  - include: imagemagick.yml
  - include: libreoffice.yml
  - include: mirror-vocabs.yml
    when: mirror_vocabularies | default([], true) | length>0
  - include: alfresco.yml
  - include: share.yml
    when: alfresco_share_install is defined and alfresco_share_install
  - include: alfviral.yml
    when: install_antivirus is defined and install_antivirus
    tags:
      - antivirus
  - include: edusharing.yml
  - include: users.yml
  - include_tasks: custom_option.yml
  - include: classification-keyword.yml
    become: true
    when: activate_classification_keywords is defined and activate_classification_keywords
  - include: jobs.yml
  - include: pixabay.yml
    when: connect_content_pixabay
  - include: youtube.yml
    when: connect_content_youtube
  - include: oersi.yml
    when: connect_content_oersi
