---
  - include: mariadb.yml
    when: alfresco_db_type == 'mariadb'
  - include: postgresql.yml
    when: alfresco_db_type == 'postgresql'
  - include: imagemagick.yml
  - include: libreoffice.yml
  - include: alfresco.yml
  - include: share.yml
    when: alfresco_share_install is defined and alfresco_share_install
  - include: alfviral.yml
    when: install_antivirus is defined and install_antivirus
    tags:
      - antivirus
  - include: edusharing.yml
  - include: users.yml
  - include: pixabay.yml
    when: connect_content_pixabay
  - include: youtube.yml
    when: connect_content_youtube
