---
  - include: mariadb.yml
  - include: imagemagick.yml
  - include: libreoffice.yml
  - include: alfresco.yml
  - include: edusharing.yml
  - include: users.yml
  - include: pixabay.yml
    when: connect_content_pixabay
