---
  - name: Ensure gzip and jq python-lxml are present.
    package:
      name:
        - unzip
        - jq
        - gzip
        - python-lxml
        - python3-lxml
    become: yes
    tags:
      - packages
      - root-task

  - name: Run Edu-Sharing version 6 and below
    include: ./edu-sharing-old/main.yml
    when: edu_version is defined and  edu_version is version_compare('7.0.0','<')
    tags:
      - edu-sharing-old

  - name: Run Edu-Sharing version 7 and above
    include: ./edu-sharing-docker/main.yml
    when: edu_version is defined and edu_version is version_compare('7.0.0','>=')
    tags:
      - edu-sharing-docker