---
- name: Ensure mysql python packages are present
  package:
    name: python-mysqldb

- name: Create a new database with name 'alfesco'
  mysql_db:
    name: '{{alfresco_db.name}}'
    encoding: 'utf8'
    collation: 'utf8_bin'
    config_file: /etc/my.cnf.d/mysql.cnf
    state: present

- name: Create alfesco database user
  mysql_user:
    name: '{{alfresco_db.user}}'
    password: '{{alfresco_db.password}}'
    priv: '{{alfresco_db.name}}.*:ALL'
