- name: register oersi - add app-oersi.properties.xml
  template:
    src: oersi.properties.xml
    dest: '{{tomcat_home}}/shared/classes/app-oersi.properties.xml'

- name: register oersi - edit applicationfiles in ccapp-registry.properties.xml
  lineinfile:
    backrefs: yes
    path: '{{ tomcat_home }}/shared/classes/ccapp-registry.properties.xml'
    line: '<entry key="applicationfiles">\g<start>\g<end>,app-oersi.properties.xml</entry>'
    regexp: '^\s*<entry key="applicationfiles">(?P<start>(?:(?!,app-oersi.properties.xml).)*)(,app-oersi.properties.xml)?(?P<end>.*?)</entry>'
