---
- name: add plugin file for OERSI as external repo
  set_fact:
    edu_sharing_plugin_files: "{{ edu_sharing_plugin_files | default([], true) + ['plugin-OERSI-as-external-repo.jar'] }}"
  when: connect_content_oersi

- name: Copy plugin files
  copy:
    src: '{{ item }}'
    dest: "{{ tomcat_home }}/webapps/edu-sharing/WEB-INF/lib/"
  loop: "{{ edu_sharing_plugin_files | default([], true) }}"

- name: Extract plugin files into classes
  command:
    chdir: '{{ tomcat_home }}/shared/classes'
    cmd: '{{ java_home }}/bin/jar xf {{ tomcat_home }}/webapps/edu-sharing/WEB-INF/lib/{{ item }} org'
  loop: "{{ edu_sharing_plugin_files | default([], true) }}"
