
- name: set shibboleth client.config configuration
  xml:
    path: '{{ edu_client_config_xml_path }}'
    xpath: '{{ item.xpath }}'
    value: '{{ item.value }}'
    pretty_print: yes
  loop:
    - xpath: /config/values/loginUrl
      value: '{{ edu_login_shib_url }}'
    - xpath: /config/values/loginAllowLocal
      value: '{{ edu_login_allow_local }}'
    - xpath: /config/values/loginProvidersUrl
      value: '{{ edu_login_providers_url | default("") }}'
    - xpath: /config/values/loginProviderTargetUrl
      value: '{{ edu_login_provider_target_url | default("") }}'
