---
- name: Ensures inst-dir exists
  file:
    path: "{{edu_connector_install_dir}}"
    state: directory


- name: Copy edu-connector docker-compose file.
  template:
    src: docker-compose.yml.j2
    dest: "{{edu_connector_install_dir}}/docker-compose.yml"

- name: Run run docker compose -d.
  shell:
    chdir: '{{edu_connector_install_dir}}/'
    cmd: 'sg docker -c "docker compose up -d"'


