- name: "wait for tomcat to come up"
  uri:
    url: '{{edu_sharing_url}}'
    timeout: 60
    status_code: 200
  register: eduConnectorResult
  until: eduConnectorResult.status == 200
  retries: 5
  delay: 1
  tags:
    - edu-connector-registration


- name: "get access token"
  uri:
    url: '{{edu_sharing_url}}/oauth2/token'
    method: POST
    body: 'grant_type=password&client_id=eduApp&client_secret=secret&username=admin&password={{alf_password}}'
    return_content: yes
  register: access_token_reply
  no_log: true
  tags:
    - edu-connector-registration

- name: "set access token"
  vars:
    jsonVar: '{{access_token_reply.content | from_json}}'
  set_fact:
    access_token: '{{jsonVar.access_token}}'
  no_log: true
  tags:
    - edu-connector-registration

- name: "remove existing edu-connector registration"
  uri:
    url: '{{edu_sharing_url}}/rest/admin/v1/applications/educonnector'
    method: DELETE
    headers:
      Authorization: 'Bearer {{access_token}}'
      Accept: application/json
    status_code: [200, 500] 
  no_log: true
  tags:
    - edu-connector-registration

- name: "register edu-connector"
  uri:
    url: '{{edu_sharing_url}}/rest/admin/v1/applications?url={{ (edu_connector_url + "/metadata") | urlencode }}'
    method: PUT
    body_format: json
    headers:
      Authorization: 'Bearer {{access_token}}'
      Accept: application/json
  # no_log: true
  tags:
    - edu-connector-registration
