---
- hosts: renderingservice
  become: yes
  roles:
    - apache
    - renderingservice-installation

- hosts: edusharing
  become: yes
  roles:
    - edu-sharing
    - apache

- hosts: edusharing
  become: yes
  roles:
    - renderingservice-init
    - renderingservice-registration
