---
- hosts: all
  become: yes
  roles:
    - set-timezone
  tags:
    - root-task

- hosts: all
  roles: 
    - init-facts

- hosts: renderingservice, edusharing
  become: yes
  roles:
    - apache
  tags:
    - root-task
    - shibboleth

- hosts: edusharing
  become: yes
  roles:
    - role: postgresql
      when: alfresco_db_type == 'postgresql'
    - role: mariadb
      when: alfresco_db_type == 'mariadb'
  tags:
    - root-task

- hosts: alfrescosolr4, edusharing
  roles:
    - java
    - role: tomcat
      tags: [ tomcat ]

- hosts: alfrescosolr4
  roles:
    - alfresco-solr4

- hosts: edusharing
  roles:
    - edu-sharing
    - role: backup
      tags: backup

- hosts: renderingservice, opencast
  become: yes
  roles:
    - role: geerlingguy.docker
      when: (install_splash is defined and install_splash) or (install_opencast_importer is defined and install_opencast_importer)
      vars:
        docker_users:
          - "{{ work_user }}"

- hosts: renderingservice
  become: yes
  roles:
    - role: postgresql
      when: esrender_db_type == 'postgresql'
    - role: mariadb
      when: esrender_db_type == 'mariadb'
    - renderingservice-installation
    - role: splash
      when: install_splash is defined and install_splash
  tags:
    - root-task

- hosts: opencast
  roles:
    - role: opencast-import
      when: install_opencast_importer is defined and install_opencast_importer

- hosts: renderingservice
  roles:
    - renderingservice-init
    - renderingservice-registration

- hosts: onlyoffice
  become: yes
  roles:
    - role: postgresql
      when: enable_only_office is defined and enable_only_office
    - role: geerlingguy.rabbitmq
      when: enable_only_office is defined and enable_only_office
    - role: nginx
      when: enable_only_office is defined and enable_only_office
    - role: onlyoffice
      when: enable_only_office is defined and enable_only_office

- hosts: edusharing
  roles:
    - role: moodle-registration
      when: register_moodle
  tags:
    - moodle-registration
    
- hosts: edusharing
  become: yes
  roles:
    - role: antivirus
      when: install_antivirus is defined and install_antivirus
      tags: antivirus
    - role: shibboleth
      when: install_shibboleth is defined and install_shibboleth
      tags: shibboleth
  tags:
    - root-task
