---
- hosts: all
  become: yes
  roles:
    - set-timezone
  tags:
    - root-task

- hosts: all
  roles:
    - init-facts

- hosts: edusharing,educonnector
  become: yes
  roles:
    - apache
  tags:
    - root-task
    - shibboleth

- hosts: edusharing
  become: yes
  roles:
    - role: geerlingguy.docker
      when: edu_version is defined and edu_version is version('7.0.0','>=')
      vars:
        docker_users:
          - "{{ work_user }}"
  tags:
    - root-task

- hosts: edusharing
  become: yes
  roles:
    - role: java
      tags: [java]

- hosts: edusharing
  roles:
    - edu-sharing

- hosts: opencast
  become: yes
  roles:
    - role: geerlingguy.docker
      when: (install_splash is defined and install_splash) or (install_opencast_importer is defined and install_opencast_importer)
      vars:
        docker_users:
          - "{{ work_user }}"

- hosts: edusharing
  become: yes
  roles:
    - role: splash
      when: install_splash is defined and install_splash
  tags:
    - root-task

- hosts: opencast
  roles:
    - role: opencast-import
      when: install_opencast_importer is defined and install_opencast_importer
  tags:
    - opencast

- hosts: educonnector
  roles:
    - role: geerlingguy.docker
      become: yes
      when: enable_edu_connector is defined and enable_edu_connector
      vars:
        docker_users:
          - "{{ work_user | default('vagrant') }}"
    - role: edu-connector
      when: enable_edu_connector is defined and enable_edu_connector
  tags:
    - edu-connector

- hosts: edusharing
  roles:
    - role: moodle-registration
      when: register_moodle
  tags:
    - moodle-registration
    
- hosts: edusharing
  become: yes
  roles:
    - role: shibboleth
      when: install_shibboleth is defined and install_shibboleth
      tags: shibboleth
  tags:
    - root-task

- hosts: antivirus
  roles:
    - role: geerlingguy.docker
      become: yes
      when: install_antivirus is defined and install_antivirus
      vars:
        docker_users:
          - "{{ work_user | default('vagrant') }}"
    - role: antivirus
      when: install_antivirus is defined and install_antivirus
  tags:
    - antivirus
    - clamav
    - clamav-docker