---
- name: "wait for tomcat to come up"
  uri:
    url: '{{edu_sharing_url}}'
    timeout: 60
    status_code: 200
  register: esresult
  until: esresult.status == 200
  retries: 5
  delay: 1
  tags:
    - esrender-registration
  
- name: "get access token"
  uri:
    url: '{{edu_sharing_url}}/oauth2/token'
    method: POST
    body: 'grant_type=password&client_id=eduApp&client_secret=secret&username=admin&password={{alf_password}}'
    return_content: yes
  register: accesstokenreply
  no_log: true
  tags:
    - esrender-registration

- name: "set access token"
  vars:
    jsonVar: '{{accesstokenreply.content | from_json}}'
  set_fact:
    accesstoken: '{{jsonVar.access_token}}'
  no_log: true
  tags:
    - esrender-registration

- name: "remove existing esrender registration"
  uri:
    url: '{{edu_sharing_url}}/rest/admin/v1/applications/esrender'
    method: DELETE
    headers:
      Authorization: 'Bearer {{accesstoken}}'
      Accept: application/json
    status_code: [200, 500] # 500 if not existing
  no_log: true
  tags:
    - esrender-registration

- name: "register esrender"
  uri:
    url: '{{edu_sharing_url}}/rest/admin/v1/applications?url={{ (esrender_url + "/application/esmain/metadata.php") | urlencode }}'
    method: PUT
    body_format: json
    headers:
      Authorization: 'Bearer {{accesstoken}}'
      Accept: application/json
  no_log: true
  tags:
    - esrender-registration
