
- set_fact:
    edu_oauth_trusted_clients_spring_config: "{{ edu_oauth_trusted_clients_spring_config | default([]) + [{'entry': {'key':item.client, 'value':item.password}}] }}"
  loop: "{{ edu_oauth_trusted_clients }}"

- name: adjust trustedClients in oauthTokenService
  xml:
    path: '{{ edu_home }}/war/WEB-INF/classes/org/edu_sharing/spring/authentication-services.xml'
    xpath: '/beans/bean[@id="oauthTokenService"]/property[@name="trustedClients"]/map'
    set_children: '{{ edu_oauth_trusted_clients_spring_config }}'
    pretty_print: yes

- name: Update authentication-services.xml in spring-configuration
  command:
    chdir: '{{ edu_home }}/war/WEB-INF/classes'
    cmd: '{{ java_home }}/bin/jar uf {{ edu_home }}/lib/edu-sharing_spring.jar org/edu_sharing/spring/authentication-services.xml'
