- name: copy edu-sharing custom sources
  copy:
    src: "{{ edu_sharing_custom_archive_path }}"
    dest: "{{edu_inst_dir}}/edu-sharing-custom.zip"

- name: extract edu-sharing custom sources into edu-home
  unarchive:
    remote_src: yes
    src: '{{edu_inst_dir}}/edu-sharing-custom.zip'
    dest: "{{edu_home}}"
