---
# -------- Menu entries (BEGIN) --------#
- name: Remove all menuEntries from client config 
  xml:
    path: '{{ edu_client_config_xml_path }}'
    xpath: "/config/values/menuEntries"
    state: absent
    pretty_print: yes

- include_tasks: ./common/custom_menu_entry.yml
  vars:
    custom_menu_entry_client_config_file: "{{edu_client_config_xml_path}}"
    custom_menu_entry_assets_path: "{{ edu_home }}/war/edu_sharing/assets"
  with_items: "{{ edu_custom_menu_entries | default([], true) }}"
  loop_control:
    loop_var: custom_menu_entry
# -------- Menu entries (END)-------- #
