---
- name: load version variables
  with_first_found:
    - '../vars/versions/{{ edu_version }}.yml'
    - '../vars/versions/default.yml'
  include_vars: '{{ item }}'
  tags:
    - edu-sharing-config
    - shibboleth

- name: Ensures inst-dir exists
  file: path='{{edu_inst_dir}}' state=directory

- name: Copy local edu-sharing artifact
  copy:
    src: "{{ edu_sharing_local_archive_path }}"
    dest: "{{edu_inst_dir}}/edu-sharing.zip"
  when: edu_sharing_archive_retrieve_method == "copy-local"

- name: Remove old installation for local artifacts
  file: path='{{edu_home}}' state=absent
  when: edu_sharing_archive_retrieve_method == "copy-local"

- name: download edu-sharing sources
  get_url:
    url: '{{edu_sharing_archive_url}}'
    dest: "{{edu_inst_dir}}/edu-sharing.zip"
  when: edu_sharing_archive_retrieve_method == "download"

- name: extract edu-sharing sources
  unarchive:
    remote_src: yes
    src: '{{edu_inst_dir}}/edu-sharing.zip'
    dest: "{{edu_inst_dir}}"
    creates: "{{edu_home}}"

- include: ./common/client-configuration.yml
    client_configuration_path='{{edu_client_config_xml_path}}'
  tags:
    - edu-sharing-config
    - client-configuration

# -------- Menu entries (BEGIN) --------#
- include: custom_menu_entries.yml
  tags:
    - edu-sharing-config
    - custom-menu-entries

# -------- Menu entries (END)-------- #

# hide main menu entries
- include: ./common/hide_main_menu.yml 
    hide_main_menu_config_xml_path='{{edu_client_config_xml_path}}'
  tags:
    - edu-sharing-config
    - hide-main-menu

- include: ./common/shibboleth_before.yml 
    shibboleth_before_path='{{edu_client_config_xml_path}}'
    edu_sharing_webapp_webinf_classes_path='{{ edu_home }}/war/WEB-INF/classes'
    edu_sharing_webapp_lib_path='{{ edu_home }}/lib'
  when: edu_configure_shibboleth is defined and edu_configure_shibboleth
  tags:
    - shibboleth
    - edu-sharing-config

- include: auth.yml
  tags: edu-sharing-config

- include: custom.yml
  when: edu_sharing_custom_installation

- name: stop alfresco
  shell: '{{ tomcat_stop_command }}'
  tags: edu-sharing-config

- include: ./common/images.yml 
    edu_sharing_images_path="{{edu_home}}/war/edu_sharing"
  tags: 
    - edu-sharing-config
    - images

- include_tasks: ./common/custom-license.yml
  vars:
    custom_license_client_config_xml_path: "{{edu_client_config_xml_path}}"
    custom_license_edu_sharing_assets: "{{ edu_home }}/war/edu_sharing"
  with_items: '{{ edu_custom_licenses | default([], true) }}'
  loop_control:
    loop_var: custom_license
  tags:
    - custom-license
#  add custom options task
- include: ./common/custom_option.yml
    custom_option_config_xml_path='{{edu_client_config_xml_path}}'
  tags:
    - custom-option
- include: ./common/editI18n.yml
    i18n_path='{{ edu_home }}/war//edu_sharing/assets/i18n'
  tags:
    - edu-sharing-config
    - i18n

- name: edit enable_statistics_api in edu-sharing.properties for versions before 5.1
  lineinfile:
    path: '{{ edu_home }}/war/WEB-INF/classes/edu-sharing.properties'
    line: 'enable_statistics_api={{ edu_enable_statistics_api }}'
    regexp: '^enable_statistics_api=.*$'
  when: edu_config_file == 'edu-sharing.properties'
  tags: edu-sharing-config

- name: use custom logging configuration if available
  copy:
    src: '{{ edu_log4j_properties_path }}'
    dest: '{{ edu_home }}/war/WEB-INF/classes/log4j.properties'
  when: (edu_log4j_properties_path is defined) and (edu_log4j_properties_path != "") and (edu_log4j_properties_path is not none)
  tags: edu-sharing-config

- name: edit edu-sharing build.properties
  lineinfile:
    path: '{{ edu_home }}/build.properties'
    line: 'webserver.home={{tomcat_home}}'
    regexp: '^webserver.home=.*$'
  tags: edu-sharing-config

- name: edit edu-sharing call-ant.sh
  replace:
    path: '{{ edu_home }}/call-ant.sh'
    replace: '{{java_home}}/bin/java '
    regexp: '^java '

- name: edit edu-sharing call-ant.sh
  replace:
    path: '{{ edu_home }}/call-ant.sh'
    replace: '-classpath '
    regexp: '-Djava.ext.dirs='

- name: make edu-sharing call-ant.sh executable
  file:
    path: '{{ edu_home }}/call-ant.sh'
    mode: 'a+x'

- name: undeploy edu-sharing
  shell: '{{ edu_home }}/call-ant.sh undeploy'
  args:
    chdir: '{{ edu_home }}'
    removes: '{{ tomcat_home }}/webapps/edu-sharing'
  tags: edu-sharing-config

- name: make edu-sharing install.sh executable
  file:
    path: '{{ edu_home }}/install.sh'
    mode: 'a+x'

- name: run edu-sharing install.sh
  shell: '{{ edu_home }}/install.sh'
  args:
    chdir: '{{ edu_home }}'
  tags: edu-sharing-config

- name: Workaround - remove libs that edu-sharing installed in the last step, because it causes version conflicts
  file:
    path: "{{ tomcat_home }}/webapps/{{ item }}"
    state: absent
  loop: '{{ edu_sharing_workaround_jar_cleanup }}'

- include: plugins.yml
  tags: edu-sharing-config

- include: ./common/edu-sharing-config-file.yml
    edu_sharing_config_file_path='{{tomcat_home}}/shared/classes/config/edu-sharing.conf'

- name: remove optional lines in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ tomcat_home }}/shared/classes/homeApplication.properties.xml'
    regexp: '<entry key="{{item}}">'
    state: absent
  loop:
    - guest_username
    - guest_password
    - allowed_authentication_types
  tags: edu-sharing-config

- name: add or edit properties in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ tomcat_home }}/shared/classes/homeApplication.properties.xml'
    line: '<entry key="{{item[0]}}">{{item[1]}}</entry>'
    regexp: '<entry key="{{item[0]}}">'
    insertbefore: '</properties>'
  loop:
    - ["appid", '{{edu_repo_id}}']
    - ["appcaption", '{{edu_repo_caption}}']
    - ["clientport", '{{ edu_sharing_clientport | default("80") }}']
    - ["port", '{{ edu_sharing_port | default("80") }}']
    - ["protocol", '{{ edu_sharing_protocol | default("http") }}']
    - ["clientprotocol", '{{ edu_sharing_clientprotocol | default("http") }}']
    - ["domain", '{{edu_sharing_domain}}']
    - ["host", '{{edu_sharing_host}}']
    - ["password", '{{alf_password}}']
  tags: edu-sharing-config

- name: activate guest-user in tomcat/shared/classes/homeApplication.properties.xml
  lineinfile:
    path: '{{ tomcat_home }}/shared/classes/homeApplication.properties.xml'
    line: '<entry key="{{item[0]}}">{{item[1]}}</entry>'
    regexp: '<entry key="{{item[0]}}">'
    insertbefore: '</properties>'
  loop:
    - ["guest_username", 'esguest']
    - ["guest_password", 'esguest']
  when : 'use_esguest_user'
  tags: edu-sharing-config

- name: edit mail properties in tomcat/shared/classes/ccmail.properties.xml
  lineinfile:
    path: '{{ tomcat_home }}/shared/classes/ccmail.properties.xml'
    line: '<entry key="{{item[0]}}">{{item[1]}}</entry>'
    regexp: '<entry key="{{item[0]}}">'
    insertbefore: '</properties>'
  loop:
    - ["mail.report.receiver", '{{edu_mail_report_receiver | default("")}}']
    - ["mail.authtype", '{{ edu_mail_authtype | default("") }}']
    - ["mail.smtp.server", '{{ edu_mail_smtp_server | default("") }}']
    - ["mail.smtp.passwd", '{{ edu_mail_smtp_passwd | default("") }}']
    - ["mail.smtp.username", '{{ edu_mail_smtp_username | default("") }}']
    - ["mail.smtp.port", '{{ edu_mail_smtp_port | default("25") }}']
    - ["mail.smtp.from", '{{ edu_mail_smtp_from | default("pleasechange@nodomain.com") }}']
  tags: edu-sharing-config

- include: ./common/shibboleth_after.yml
    shibboleth_after_path='{{ tomcat_home }}/shared/classes'
  when: edu_configure_shibboleth is defined and edu_configure_shibboleth
  tags:
    - shibboleth
    - edu-sharing-config

- include: ./common/metadatasets.yml 
      metadatasets_directory_path='{{ tomcat_home }}/shared/classes/org/edu_sharing/metadataset/v2/'
  tags: 
    - edu-sharing-config
    - metadatasets

- include: model.yml
  tags: edu-sharing-config

- include: ./common/lms.yml 
    lms_path='{{ tomcat_home }}/shared/classes'
  tags: 
    - edu-sharing-config
    - lms

- include: ./common/mail-templates.yml
    mail_templates_path="{{ tomcat_home }}/shared/classes/org/edu_sharing/repository/server/tools/mailtemplates/"
  tags: 
    - edu-sharing-config
    - mail-templates

- name: start alfresco
  shell: '{{tomcat_start_command}}'
  tags: edu-sharing-config
