---
  - include: mariadb.yml
    when: alfresco_db_type == 'mariadb'
  - include: postgresql.yml
    when: alfresco_db_type == 'postgresql'
    tags:
      - backup
  - include: imagemagick.yml
  - include: libreoffice.yml
  - include: ./common/mirror-vocabs.yml
    when: mirror_vocabularies | default([], true) | length>0
  - include: alfresco.yml
  - include: share.yml
    when: alfresco_share_install is defined and alfresco_share_install
  - include: ./common/alfviral.yml 
        alf_amp_destination='{{ alf_home }}/amps/'
        old_install_alfviral=true
    when: install_antivirus is defined and install_antivirus
  - include: ./common/es_update_oersi.yml 
        es_amp_destination='{{ alf_home }}/amps/'
        old_install_es_update_oersi=true
    when: activate_es_update_oersi is defined and activate_es_update_oersi
    tags:
      - es-update-oersi-old
      - es-update-oersi
  - include: ./common/add_alviral_to_alfresco_properties.yml 
        alfresco_global_properties_path='{{tomcat_home}}/shared/classes'
    when:  install_antivirus is defined and  install_antivirus
    tags:
    - alfviral
    - antivirus-old
  - include: ./common/add_es_update_oersi_to_alfresco_properties.yml 
        alfresco_global_properties_path='{{tomcat_home}}/shared/classes'
    when:  activate_es_update_oersi is defined and  activate_es_update_oersi    
    tags:
      - es-update-oersi-old
      - es-update-oersi
  - include: ./common/add_mail_config_to_alfresco_properties.yml
      alfresco_global_properties_path='{{tomcat_home}}/shared/classes'
    tags:
      - mail
      - mail-old-version
  - include: edusharing.yml
  - include: users.yml
  - include: ./common/classification-keyword.yml
    become: true
    when: activate_classification_keywords is defined and activate_classification_keywords
    tags:
      - classification-keyword
  - include: ./common/jobs.yml
      jobs_edu_sharing_url="{{edu_sharing_url}}"
    tags:
      - jobs
  - include: ./common/pixabay.yml 
        pixabay_path='{{ tomcat_home }}/shared/classes'
    when: connect_content_pixabay
    tags:
      - pixabay
  - include: ./common/youtube.yml 
      youtube_path='{{ tomcat_home }}/shared/classes'
    when: connect_content_youtube
    tags:
      - youtube
  - include: oersi.yml
    when: connect_content_oersi
