---
  - include: mariadb.yml
    when: alfresco_db_type == 'mariadb'
  - include: postgresql.yml
    when: alfresco_db_type == 'postgresql'
    tags:
      - backup
  - include: imagemagick.yml
  - include: libreoffice.yml
  - include: ./common/mirror-vocabs.yml
    when: mirror_vocabularies | default([], true) | length>0
  - include: alfresco.yml
  - include: share.yml
    when: alfresco_share_install is defined and alfresco_share_install
  - include: alfviral.yml
    when: install_antivirus is defined and install_antivirus
    tags:
      - antivirus
  - include: edusharing.yml
  - include: users.yml
  - include: ./common/classification-keyword.yml
    become: true
    when: activate_classification_keywords is defined and activate_classification_keywords
    tags:
      - classification-keyword
  - include: ./common/jobs.yml
      jobs_edu_sharing_url="{{edu_sharing_url}}"
    tags:
      - jobs
  - include: ./common/pixabay.yml 
        pixabay_path='{{ tomcat_home }}/shared/classes'
    when: connect_content_pixabay
    tags:
      - pixabay
  - include: ./common/youtube.yml 
      youtube_path='{{ tomcat_home }}/shared/classes'
    when: connect_content_youtube
    tags:
      - youtube
  - include: oersi.yml
    when: connect_content_oersi
