# Debian Bullseye (11) +

- name: Check if SWITCHaai-swdistrib.list exists
  stat:
    path: /etc/apt/sources.list.d/SWITCHaai-swdistrib.list
  register: switchaai_sources_list_stat_result

- include_tasks: migrate-from-switchaai.yml
  when: switchaai_sources_list_stat_result.stat.exists

- name: Install shibboleth package for debian
  apt:
    update_cache: yes
    name: libapache2-mod-shib
