# installation documentation debian:
# https://www.switch.ch/aai/guides/sp/installation/?os=debian9

# Fail for unsupported versions
- fail: msg='unsupported OS version {{ ansible_distribution }} {{ ansible_distribution_release }}'
  vars:
    supported_versions:
      - 'Debian stretch'
  when: (ansible_distribution + ' ' + ansible_distribution_release) not in supported_versions
  
- include: debianstretch.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'

- include: shibbolethconfig.yml
