---
- set_fact: edu_docker_inst_dir="{{ edu_inst_dir|replace('.','_') }}"

- include_role:
    name: edu-sharing-init
    tasks_from: load_version_variables
    apply:
      tags:
        - edu-sharing-search-elastic
  tags:
    - edu-sharing-search-elastic

- include_tasks: config-env.yml
  when: rendering_environment_variable | default([], true) | length>0
  tags: 
    - edu-sharing-search-elastic

- name: restart rendering-service in docker.
  command:
    chdir: "{{ edu_docker_inst_dir }}"
    cmd: "{{edu_sharing_restart_command | replace('{service}', 'repository-search-elastic-index repository-search-elastic-tracker') }}"
  # no_log: true
  tags:
    - edu-sharing-search-elastic